import { Box, Container, MenuItem, Paper, Stack, Toolbar } from "@mui/material";
import Head from 'next/head';

import Header from "components/navigation";
import Link from "next/link"

export default function PageContainer({ children, isNav = true }) {

    return (
        <Box sx={{ bgcolor: (t) => t.palette.common.white }}>
            <Container
                maxWidth="xl"
                sx={{
                    minHeight: '100vh',
                    display: 'grid',
                    placeItems: isNav ? 'top' : 'center',
                }}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Paper elevation={12} sx={{
                    bgcolor: (t) => t.palette.common.white,
                    height: "90vh",
                    width: '100%',
                    p: 2,
                    borderRadius: 0,
                }}>
                    { isNav && <Header /> }
                    {children}
                </Paper>
            </Container>
        </Box>
    )
}